### ISSUE TITLE
reconstruct command has `when: always`?

### ISSUE THREAD

**Issue by jrnail23** [iynere/compare-url#31]
### Orb version
v1.1.0

### What happened

Hi @iynere, when using this orb, I had a hell of a time figuring out why my job wasn't stopping when a validation step was failing before the `reconstruct` command started... I didn't realize that `reconstruct` has `when: always`.
Is there a way to override that behavior?  There's a lot going on in `reconstruct`, and when it fails, there's a lot of console noise, making it easy to miss any preceding failures (which is what bit me).  It just doesn't seem like the kind of command that adds value after a failing step.  Your thoughts?

### Expected behavior

I'd prefer if the command's `when` attribute to be parameterized.

**Comment by iynere** [comment]
that's a reasonable request @jrnail23 wanna PR it ? should be a super easy change. thank you !

**Comment by jrnail23** [comment]
@iynere -- just a gentle nudge: my PR is available for your review (#32)

**Comment by iynere** [comment]
ah, thank you ! @jrnail23 apologies, will 👀 today

**Comment by iynere** [comment]
merged ! @jrnail23
